site_name: BadgePirates Documents
site_url: https://bpdocs.github.io/docs/
repo_url: https://github.com/BPDocs/docs/
edit_uri: https://github.com/BPDocs/docs/edit/main/docs



theme:
  name: material
  logo: img/badgepirates.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    
    - media: "(prefers-color-scheme: light)"
      scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: blue grey
      accent: lime

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BadgePiratesLLC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/BadgePirates
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kevin-bennett-leessummit/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/badgepiratesllc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BfsYbHY8m7
nav:
  - Home: index.md
  - Build Guides:
      - badge1: bg/badge1.md
      - badge2: bg/badge2.md
  - Misc:
      - MiscDoc1: misc/misc1.md
  - FAQ: faq/index.md
